[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gemini-cli-core"
version = "0.1.0"
description = "Gemini CLI core functionality implemented with Python and LangGraph"
authors = [
    {name = "Gemini CLI Team"},
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.2.0",
    "langchain>=0.3.0",
    "langchain-google-genai>=2.0.0",
    "fastapi>=0.115.0",
    "uvicorn>=0.30.1",
    "sse-starlette>=2.1.0",
    "websockets>=13.0",
    "pydantic>=2.9.0",
    "aiofiles>=24.1.0",
    "httpx>=0.27.0",
    "html2text>=2024.2.26",
    "gitpython>=3.1.0",
    "pathspec>=0.12.1",
    "docker>=7.1.0",
    "mcp>=1.10.0",
    "python-dotenv>=1.0.0",
    "structlog>=24.4.0",
    "opentelemetry-api>=1.28.0",
    "opentelemetry-sdk>=1.28.0",
    "opentelemetry-exporter-otlp>=1.28.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.0",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=5.0.0",
    "mypy>=1.13.0",
    "ruff>=0.8.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.ruff]
line-length = 80
target-version = "py312"
fix = true

[tool.ruff.format]
# 使用 ruff 格式化
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
    "ALL", # 包括所有规则，包括新的
]
ignore = [
    #### 模块
    "ANN", # flake8-annotations
    "COM", # flake8-commas
    "C90", # mccabe 复杂度
    "DJ",  # django
    "EXE", # flake8-executable
    "T10", # 调试器
    "TID", # flake8-tidy-imports

    #### 特定规则
    "BLE001",
    "D100",   # 忽略缺失的文档
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D203",   # 类定义前需要空行 (与 D211 冲突)
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "DTZ005", # 忽略时区警告
    "E402",   # 本地导入的误报
    "E501",   # 行太长
    "EM102",
    "G004",   # f-string
    "ERA001",
    "FBT001",
    "FBT002",
    "TRY003", # 异常中的外部消息太冗长
    "TD002",
    "TD003",
    "T201",
    "FIX002", # todo 的描述太冗长
    "RUF001",
    "RUF002",
    "RUF003",
]

[tool.mypy]
python_version = "3.12"
strict = true
warn_return_any = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"